name: Release

on:
  push:
    tags:
      - 'v*' # Run when tag matches v*, i.e. v1.0.0, v20.15.10

permissions:
  contents: write # Needed to create releases

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all tags

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true

      - name: Get version from tag
        id: get_version
        run: echo "APP_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Run build script with version
        run: chmod +x ./build.sh && ./build.sh ${{ env.APP_VERSION }}

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Firefox Bookmarks Converter v${{ env.APP_VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            builds/ff_bookmarks_windows_amd64.exe
            builds/ff_bookmarks_windows_arm64.exe
            builds/ff_bookmarks_macos_intel
            builds/ff_bookmarks_macos_arm64
            builds/ff_bookmarks_linux_amd64
            builds/ff_bookmarks_linux_arm64
